### ISSUE TITLE
 ValueError: unsupported pickle protocol: 3 in python27

### ISSUE THREAD

**Issue by vansdev** [indrajithi/mgc-django#2]
get this error when trying to run your app in python2.7
then tried this 

```
filename = 'classifier_10class.pkl'
with open(filename, 'r') as f:
    x = pickle.load(f)
```

get: 

> ValueError: unsupported pickle protocol: 3

it seems that the pkl files were created with protocol 3 which is **only** available in python3
not sure if this is the case or i did not run the app in the right way

**Comment by indrajithi** [comment]
You run the App in right way. It will not work in python2. 
The file `classifier_10class.pkl`  is actually a dump from `joblib` from `sklearn.externals`. I did the dump by using python3. The default protocol is 3 and in order for that to work in python2 we should have used a pickle protocol less than 3 while dump. `mysvm` package was written for python 3. 

If you want to use in python2. You can use this `data/Xall.npy` which contains X values for training and generate Y value by using `mysvm.feature.geny(n) `and fit a poly kernel svm by using 
```
clf = svm.SVC(kernel='poly',C=1,probability=True)
clf.fit(X,Y)
```
