### ISSUE TITLE
Frontend Dependencies

### ISSUE THREAD

**Issue by coreyar** [indrajithi/mgc-django#3]
I came upon this repo from the Python Weekly newsletter. I saw that there was no build process for frontend dependencies. I dug around a bit and didn't find a clear path to separate them out. Is that something is on the roadmap for the project?

**Comment by indrajithi** [comment]
I have not written much frontend code myself. Most of the front end code is taken from this project `https://github.com/blueimp/jQuery-File-Upload`.
